package com.layermark.interviewtask.vaccine;

import com.layermark.interviewtask.doctor.Doctor;
import com.layermark.interviewtask.patient.Patient;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * This class defines the Vaccine entity (object) and all of its attributes (properties) and its relations and methods
 */

@Entity(name="Vaccine")
@Table(
        name="vaccine",
        uniqueConstraints = @UniqueConstraint(name="vaccine_name_unique", columnNames = "name")
)
public class Vaccine {

    // properties
    @Id
    @SequenceGenerator(
            name = "vaccine_sequence",
            sequenceName = "vaccine_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "vaccine_sequence"
    )
    @Column(
            name = "id",
            updatable = false
    )
    private Long id;
    @Column(
            name = "name",
            nullable = false
    )
    private String name;

    @ManyToMany
    @JoinTable(
            name = "patient_vaccinated",
            joinColumns = @JoinColumn(name = "vaccine_id"),
            inverseJoinColumns = @JoinColumn(name = "patient_id")
    )
    private Set<Patient> patients = new HashSet<>();

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(
            name = "doctor_id",
            referencedColumnName = "id"
    )
    private Doctor doctor;

    // constructors
    public Vaccine() {} // default constructor

    public Vaccine(Long id, String name) {
        this.id = id;
        this.name = name;
    } // constructor with all properties

    public Vaccine(String name) {
        this.name = name;
    } // constructor without id since it will be generated by the database

    // accessor methods
    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }

    public Set<Patient> getPatients() { return patients; }

    public Doctor getDoctor() { return doctor; }

    public void vaccinatePatient(Patient patient) {
        if (!this.patients.contains(patient)) {
            this.patients.add(patient);
        }
    }

    public void assignDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    //overridden toString method
    @Override
    public String toString() {
        return "Vaccine { id = " + id + ", name = \"" + name + '"' +"}";
    }
}
